version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents:ro  # Mount documents directory
      - ./src/utils/vectorstore:/app/src/utils/vectorstore
    environment:
      - DOC_PATH=/app/documents/Tender_Specs_ECDC2024OP0017_V1.pdf  # Use absolute path
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
